name: "Clone Private Repo"
description: "Clone Private Repo"

inputs:
  github-deploy-key:
    description: "GitHub Deploy Key"
    required: true
  repository:
    description: "Repository, eg: git@github.com:LUPARG/c-k8s-helm-chart.git"
    required: true
  clone-path:
    description: "Path"
    required: true
  extra-commands:
    description: "Eg: rm -r ./devops/argocd/k8s-helm-chart/.git"
    required: true

runs:
  using: "composite"
  steps:
    - name: Clone Private Repo
      shell: bash
      id: clone-private-repo
      env:
        GITHUB_DEPLOY_KEY: ${{ inputs.github-deploy-key }}
        REPOSITORY: ${{ inputs.repository }}
        CLONE_PATH: ${{ inputs.clone-path }}
        EXTRA_COMMANDS: ${{ inputs.extra-commands }}
      run: |
        # add deploy key to ssh agent
        eval `ssh-agent -s`
        ssh-add - <<< '$GITHUB_DEPLOY_KEY'

        # git clone
        git clone $REPOSITORY $CLONE_PATH
        $EXTRA_COMMANDS
