name: "SSM Secret Fetch"
description: "Fetch an secret from AWS Parameter Store"

inputs:
  aws-region:
    description: “AWS Region”
    required: true
  secret-path:
    description: "Secret Path"
    required: true

outputs:
  ssm-secret:
    description: "SSM Secret"
    value: ${{steps.ssm-retrieve.outputs.ssm-secret}}

runs:
  using: "composite"
  steps:
    - name: Retrieve SSM Secret
      shell: bash
      id: ssm-retrieve
      env:
        AWS_REGION: ${{ inputs.aws-region }}
        SECRET_PATH: ${{ inputs.secret-path }}
      run: |

        # FETCH SSM SECRET
        SSM_SECRET=$(aws ssm get-parameter --name $SECRET_PATH --query "Parameter.Value" --output text --with-decryption --region $AWS_REGION)

        # RESOLVE MULTILINE ISSUE DESCRIBED HERE https://github.com/orgs/community/discussions/26288#discussioncomment-3876281
        delimiter="$(openssl rand -hex 8)"
        echo "ssm-secret<<${delimiter}" >> "${GITHUB_OUTPUT}"
        echo "$SSM_SECRET" >> "${GITHUB_OUTPUT}"
        echo "${delimiter}" >> "${GITHUB_OUTPUT}"
