name: "Install ECS CLI"
description: "Install ECS CLI"

runs:
  using: "composite"
  steps:
    - name: Instal ECS CLI
      shell: bash
      id: install-ecs-cli
      run: |

        # INSTALL ECS CLI
        sudo curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
