name: devops-build
on:
- workflow_call
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Select Environment
      id: select-environment
      uses: INFRALESS-IO/github-actions/.github/actions/select-environment@feature/devops-from-master