name: devops-build
on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      clone-k8s-helm-chart-repository:
        required: true
        type: string
      clone-k8s-helm-chart-repository-tag:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Select Environment
      id: select-environment
      uses: INFRALESS-IO/github-actions/.github/actions/select-environment@feature/devops-from-master

    - name: Assume InfraDeployGitHub
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: ap-southeast-2
        role-to-assume: arn:aws:iam::498179384503:role/CIDeployGitHub
        role-duration-seconds: 1800

    - name: Install AWS CLI
      id: install-aws-cli
      uses: INFRALESS-IO/github-actions/.github/actions/install-aws-cli@0.0.17

    - name: Install ARGOCD CLI
      id: install-argocd-cli
      uses: INFRALESS-IO/github-actions/.github/actions/install-argocd-cli@0.0.17

    - name: Install TELEPORT CLI
      id: install-teleport-cli
      uses: INFRALESS-IO/github-actions/.github/actions/install-teleport-cli@0.0.17

    - name: Fetch GitHub Deploy Key
      id: ssm-secret-fetch-github-deploy-key
      uses: INFRALESS-IO/github-actions/.github/actions/ssm-secret-fetch@0.0.17
      with:
        aws-region: "${{ inputs.aws-region }}"
        secret-path: "/common/github/c-k8s-helm-chart/deploy-key"

    - name: Fetch ArgoCD Username
      id: ssm-secret-fetch-argocd-username
      uses: INFRALESS-IO/github-actions/.github/actions/ssm-secret-fetch@0.0.17
      with:
        aws-region: "ap-southeast-2"
        secret-path: "/${{steps.select-environment.outputs.environment}}/github/argocd/argocd-username"

    - name: Fetch ArgoCD Password
      id: ssm-secret-fetch-argocd-password
      uses: INFRALESS-IO/github-actions/.github/actions/ssm-secret-fetch@0.0.17
      with:
        aws-region: "${{ inputs.aws-region }}"
        secret-path: "/${{steps.select-environment.outputs.environment}}/github/argocd/argocd-password"

    - name: Fetch Teleport Key
      id: ssm-secret-fetch-teleport-key
      uses: INFRALESS-IO/github-actions/.github/actions/ssm-secret-fetch@0.0.17
      with:
        aws-region: "${{ inputs.aws-region }}"
        secret-path: "/common/github/teleport/teleport-key"

    - name: CLONE K8S HELM CHART
      id: clone-k8s-helm-chart
      uses: INFRALESS-IO/github-actions/.github/actions/clone-private-repo@0.0.17
      with:
        github-deploy-key: "${{steps.ssm-secret-fetch-github-deploy-key.outputs.ssm-secret}}"
        repository: "${{ inputs.clone-k8s-helm-chart-repository }}"
        repository-tag: "${{ inputs.clone-k8s-helm-chart-repository-tag }}"
        clone-path: "./devops/argocd/k8s-helm-chart"
        extra-commands: "rm -r ./devops/argocd/k8s-helm-chart/.git"