name: devops-deploy
on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      argocd-extra-params:
        required: true
        type: string
      teleport-url:
        required: true
        type: string
      environment:
        required: true
        type: string
      release-tag:
        required: true
        type: string
      argocd-username:
        required: true
        type: string
      argocd-password:
        required: true
        type: string
      teleport-key:
        required: true
        type: string
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install ARGOCD CLI
      id: install-argocd-cli
      uses: INFRALESS-IO/github-actions/.github/actions/install-argocd-cli@feature/devops-from-master

    - name: Update ARGOCD Release
      id: update-argocd-release
      uses: INFRALESS-IO/github-actions/.github/actions/update-argocd-release@0.0.17
      with:
        environment: "${{ inputs.environment }}"
        release-tag: "${{ inputs.release-tag }}"
        app-name: "${{ inputs.app-name }}"
        argocd-username: "${{ inputs.argocd-username }}"
        argocd-password: "${{ inputs.argocd-password }}"
        argocd-timeout-seconds: "360"
        argocd-extra-params: "${{ inputs.argocd-extra-params }}"
        teleport-key: ${{ inputs.teleport-key }}
        teleport-url: "${{ inputs.teleport-url }}"
        teleport-bastion: bastion-${{ inputs.environment }}

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{steps.select-environment.outputs.release-tag}}
        release_name: Release ${{steps.select-environment.outputs.release-tag}}
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        generate_release_notes: true