name: Build
on:
  push:
    branches:
      - "test-ssm-fecth-ga"
      
permissions: write-all
jobs:
  test-ssm-fetch:
    name: Test SSM Fetch
    runs-on: ubuntu-latest
    # needs: tests
    steps:
    - uses: actions/checkout@v3

    - name: Assume InfraDeployGitHub
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: 'us-west-1'
        # An IAM role with permission to run CDK against all environments, found in our AWS Account "Common"
        role-to-assume: arn:aws:iam::874302534186:role/CIDeployGitHub
        role-duration-seconds: 1800
      
    - name: Retrieve SSM Multiline Secret
      shell: bash
      id: ssm-multi-retrieve
      env:
        AWS_REGION: 'us-west-1'
        SECRET_PATH: '/common/github/teleport/teleport-key'
      run: |

        # FETCH SSM SECRET
        SSM_SECRET=$(aws ssm get-parameter --name $SECRET_PATH --query "Parameter.Value" --output text --with-decryption --region $AWS_REGION)

        # echo $SSM_SECRET

        delimiter="$(openssl rand -hex 8)"
        echo "ssm-secret<<${delimiter}" >> "${GITHUB_OUTPUT}"
        echo "$SSM_SECRET" >> "${GITHUB_OUTPUT}"
        echo "${delimiter}" >> "${GITHUB_OUTPUT}"

    - name: Show SSM Multiline Secret
      shell: bash
      run: |
        touch temp
        echo "${{steps.ssm-multi-retrieve.outputs.ssm-secret}}" > temp
        cat temp


    - name: Retrieve SSM Single line Secret
      shell: bash
      id: ssm-single-retrieve
      env:
        AWS_REGION: 'us-west-1'
        SECRET_PATH: '/staging-1/github/argocd/argocd-password'
      run: |

        # FETCH SSM SECRET
        SSM_SECRET=$(aws ssm get-parameter --name $SECRET_PATH --query "Parameter.Value" --output text --with-decryption --region $AWS_REGION)

        # echo $SSM_SECRET

        delimiter="$(openssl rand -hex 8)"
        echo "ssm-secret<<${delimiter}" >> "${GITHUB_OUTPUT}"
        echo "$SSM_SECRET" >> "${GITHUB_OUTPUT}"
        echo "${delimiter}" >> "${GITHUB_OUTPUT}"

    - name: Show SSM Single Secret
      shell: bash
      run: |
        touch temp
        echo "${{steps.ssm-single-retrieve.outputs.ssm-secret}}" > temp
        cat temp
  